#!/usr/bin/env node
/**
 * P1 HITL waitForOperator proof (file handshake, no real human).
 *
 * - HITL_MODE=manual fail-closed without waiter → HitlBlockedError
 * - Manual + file waiter: writes evidence/hitl-proof/*, resumes on hitl-resume.json
 * - Does not read or copy .env / API keys into evidence
 *
 * Usage: node scripts/hitl-proof.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { spawn } from "node:child_process";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const proofDir = path.join(root, "evidence", "hitl-proof");
const resumeFile = path.join(proofDir, "hitl-resume.json");

function wipeProofDir() {
  fs.rmSync(proofDir, { recursive: true, force: true });
  fs.mkdirSync(proofDir, { recursive: true });
}

function writeReadme() {
  const readme = `# HITL proof pack (file handshake)

Generated by \`scripts/hitl-proof.mjs\` under \`HITL_MODE=manual\`.

## Handoff flow

1. Automation calls \`escalateToHuman\` with \`waitForOperator\` from \`src/hitl/wait-for-operator.ts\`.
2. Driver \`pauseForHuman()\` yields the **same** live session (\`sessionId\` + attach instructions).
3. Waiter writes \`intervention-request.json\`, \`attach-instructions.txt\`, and appends \`pause-log.txt\`.
4. Operator (or this script) writes \`hitl-resume.json\` with \`{ "operatorNotes": "…" }\`.
5. Waiter returns notes → \`handle.resume()\` → control returns to automation.

## Fail-closed

Without \`waitForOperator\`, manual mode throws \`HitlBlockedError\` (no silent auto-resume).
See \`fail-closed.json\` in this directory and \`tests/unit/hitl.test.ts\`.

## Files

| File | Purpose |
|------|---------|
| \`intervention-request.json\` | InterventionRequest + sessionId + attach |
| \`attach-instructions.txt\` | How to attach to the live session |
| \`pause-log.txt\` | Pause / resume timeline |
| \`hitl-resume.json\` | Operator resume signal |
| \`operator-notes.txt\` | Notes accepted by waiter |
| \`fail-closed.json\` | Evidence that missing waiter throws |
| \`intervention-result.json\` | Resume result from escalateToHuman |
| \`README.md\` | This file |

No \`.env\`, API keys, or secrets are copied here.

## Re-run

\`\`\`bash
node scripts/hitl-proof.mjs
\`\`\`
`;
  fs.writeFileSync(path.join(proofDir, "README.md"), readme, "utf8");
}

function runPhase(phase) {
  const runnerPath = path.join(root, ".tmp", "hitl-proof-runner.ts");
  const code = `
import fs from "node:fs";
import { escalateToHuman } from "../src/hitl/handoff.ts";
import { createFileWaitForOperator, writeResumeSignal } from "../src/hitl/wait-for-operator.ts";
import { RunLogger } from "../src/observability/logger.ts";

const proofDir = process.env.HITL_PROOF_DIR!;
const resumeFile = process.env.HITL_RESUME_FILE!;

function stubDriver() {
  return {
    kind: "web" as const,
    open: async () => {},
    close: async () => {},
    observe: async () => ({
      url: "http://127.0.0.1:4173/",
      title: "t",
      accessibilityTree: "",
      visibleText: "",
      frames: [],
    }),
    click: async () => {},
    fill: async () => {},
    select: async () => {},
    press: async () => {},
    navigate: async () => {},
    waitFor: async () => {},
    readText: async () => "",
    isVisible: async () => false,
    screenshot: async () => {},
    pauseForHuman: async () => ({
      attachInstructions: "Stub HITL: headed Playwright page retained (proof script; no CDP attach).",
      sessionId: "sess-hitl-proof",
      resume: async () => {},
    }),
  };
}

const request = {
  reason: "replay stuck (proof)",
  capabilityName: "lookup_member_savings_balance",
  stepId: "step-proof",
  observedSummary: "element_not_found (scripted proof)",
  createdAt: new Date().toISOString(),
};

async function main() {
  process.env.HITL_MODE = "manual";
  const phase = process.argv[2];
  const logDir = proofDir + "/run-logs";
  fs.mkdirSync(logDir, { recursive: true });

  if (phase === "fail-closed") {
    const logger = new RunLogger({ runId: "hitl-fail-closed", dir: logDir });
    let errName: string | null = null;
    let errMessage: string | null = null;
    try {
      await escalateToHuman({ driver: stubDriver() as any, logger, request });
    } catch (e: any) {
      errName = e?.name ?? "Error";
      errMessage = e?.message ?? String(e);
    }
    await logger.close();
    const ok = errName === "HitlBlockedError";
    fs.writeFileSync(
      proofDir + "/fail-closed.json",
      JSON.stringify({ ok, errName, errMessage, mode: "manual", waiter: false }, null, 2) + "\\n",
    );
    if (!ok) {
      console.error("fail-closed did not throw HitlBlockedError", errName, errMessage);
      process.exit(2);
    }
    console.log(JSON.stringify({ phase, ok: true }));
    return;
  }

  if (phase === "resume") {
    const logger = new RunLogger({ runId: "hitl-resume", dir: logDir });
    const waiter = createFileWaitForOperator({
      proofDir,
      resumeFile,
      pollMs: 50,
      timeoutMs: 15_000,
    });

    const escalatePromise = escalateToHuman({
      driver: stubDriver() as any,
      logger,
      request,
      waitForOperator: waiter,
    });

    const reqPath = proofDir + "/intervention-request.json";
    const deadline = Date.now() + 10_000;
    while (!fs.existsSync(reqPath) && Date.now() < deadline) {
      await new Promise((r) => setTimeout(r, 50));
    }
    if (!fs.existsSync(reqPath)) {
      console.error("intervention-request.json never appeared");
      process.exit(3);
    }
    writeResumeSignal(resumeFile, "Operator cleared gate (hitl-proof script).", {
      sessionId: "sess-hitl-proof",
    });

    const result = await escalatePromise;
    await logger.close();
    fs.writeFileSync(
      proofDir + "/intervention-result.json",
      JSON.stringify(result, null, 2) + "\\n",
    );
    if (result.mode !== "manual" || !result.operatorNotes.includes("hitl-proof")) {
      console.error("unexpected result", result);
      process.exit(4);
    }
    console.log(JSON.stringify({ phase, ok: true, result }));
    return;
  }

  console.error("unknown phase", phase);
  process.exit(1);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
`;
  fs.mkdirSync(path.dirname(runnerPath), { recursive: true });
  fs.writeFileSync(runnerPath, code, "utf8");

  return new Promise((resolve, reject) => {
    const child = spawn("npx", ["tsx", runnerPath, phase], {
      cwd: root,
      env: {
        ...process.env,
        HITL_MODE: "manual",
        HITL_PROOF_DIR: proofDir,
        HITL_RESUME_FILE: resumeFile,
      },
      stdio: ["ignore", "pipe", "pipe"],
    });
    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (d) => {
      stdout += d.toString();
    });
    child.stderr.on("data", (d) => {
      stderr += d.toString();
    });
    child.on("close", (code) => {
      if (code !== 0) {
        reject(new Error(`phase ${phase} exit ${code}\nstdout:${stdout}\nstderr:${stderr}`));
      } else {
        resolve({ stdout, stderr });
      }
    });
  });
}

function assertNoSecrets() {
  const forbidden = [/sk-[a-zA-Z0-9]{10,}/, /OPENAI_API_KEY\s*=/, /Bearer\s+[A-Za-z0-9._\-]+/];
  function walk(dir) {
    for (const f of fs.readdirSync(dir)) {
      const p = path.join(dir, f);
      const st = fs.statSync(p);
      if (st.isDirectory()) walk(p);
      else {
        const text = fs.readFileSync(p, "utf8");
        for (const re of forbidden) {
          if (re.test(text)) throw new Error(`Secret-like pattern in evidence: ${p}`);
        }
      }
    }
  }
  walk(proofDir);
  if (fs.existsSync(path.join(proofDir, ".env"))) throw new Error(".env must not be in evidence");
}

async function main() {
  console.log("HITL proof →", proofDir);
  wipeProofDir();
  writeReadme();

  const fail = await runPhase("fail-closed");
  console.log("fail-closed:", fail.stdout.trim());

  const resume = await runPhase("resume");
  console.log("resume:", resume.stdout.trim());

  writeReadme();
  assertNoSecrets();

  const expected = [
    "intervention-request.json",
    "attach-instructions.txt",
    "pause-log.txt",
    "hitl-resume.json",
    "operator-notes.txt",
    "fail-closed.json",
    "intervention-result.json",
    "README.md",
  ];
  for (const f of expected) {
    if (!fs.existsSync(path.join(proofDir, f))) {
      throw new Error(`missing evidence file: ${f}`);
    }
  }

  console.log(JSON.stringify({ ok: true, proofDir, files: fs.readdirSync(proofDir) }, null, 2));
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
